### ISSUE TITLE
Failed to load the language-meta-script package

### ISSUE THREAD

**Issue by mk8** [metascript/language-metascript#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [language-meta-script](https://github.com/metascript/language-metascript) package, v0.0.2
### Stack Trace

Failed to load the language-meta-script package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\torello\.atom\packages\language-meta-script\lib\language-meta-script-view.coffee:1:1)
    at C:\Users\torello\.atom\packages\language-meta-script\lib\language-meta-script-view.coffee:7:3
    at Object.<anonymous> (C:\Users\torello\.atom\packages\language-meta-script\lib\language-meta-script-view.coffee:7:3)
    at Object.<anonymous> (C:\Users\torello\.atom\packages\language-meta-script\lib\language-meta-script-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\torello\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
language-docker, v1.1.3
language-gradle, v0.0.3
language-meta-script, v0.0.2
minimap, v4.15.0

# Dev
No dev packages
```

**Comment by massimiliano-mantione** [comment]
Fixed in 0.0.4
